"""
Export INSERT statements for: users, warehouses, floors, areas, zones, shelves
Output: seed_data_export.sql
"""
import os
import psycopg2
from dotenv import load_dotenv

load_dotenv()

RAW_URL = os.getenv("DATABASE_URL", "")
# Parse DATABASE_URL: postgresql://user:pass@host:port/dbname
url = RAW_URL.replace("postgresql+psycopg2://", "").replace("postgresql://", "")
# format: user:pass@host:port/dbname
userpass, rest = url.split("@", 1)
user, password = userpass.split(":", 1)
hostport, dbname = rest.split("/", 1)
if ":" in hostport:
    host, port = hostport.split(":")
else:
    host, port = hostport, "5432"

TABLES = ["users", "warehouses", "floors", "areas", "zones", "shelves"]

conn = psycopg2.connect(
    dbname=dbname.strip(),
    user=user.strip(),
    password=password.strip(),
    host=host.strip(),
    port=int(port.strip()),
)

output_lines = []
output_lines.append("-- =====================================================")
output_lines.append("--  OptiWare WMS  –  Seed Data Export")
output_lines.append("--  Tables: users, warehouses, floors, areas, zones, shelves")
output_lines.append("--  Generated by export_seed_data.py")
output_lines.append("-- =====================================================\n")
output_lines.append("-- Disable triggers / FK checks for clean import")
output_lines.append("SET session_replication_role = replica;\n")

with conn.cursor() as cur:
    for table in TABLES:
        # Get column names
        cur.execute(
            "SELECT column_name FROM information_schema.columns "
            "WHERE table_schema = 'public' AND table_name = %s "
            "ORDER BY ordinal_position",
            (table,),
        )
        columns = [row[0] for row in cur.fetchall()]

        if not columns:
            output_lines.append(f"-- [SKIP] Table '{table}' not found or has no columns.\n")
            continue

        cur.execute(f'SELECT * FROM public."{table}"')
        rows = cur.fetchall()

        output_lines.append(f"-- ---------------------------------------------------")
        output_lines.append(f"-- Table: {table}  ({len(rows)} rows)")
        output_lines.append(f"-- ---------------------------------------------------")

        if not rows:
            output_lines.append(f"-- (no data)\n")
            continue

        col_list = ", ".join(f'"{c}"' for c in columns)

        for row in rows:
            vals = []
            for v in row:
                if v is None:
                    vals.append("NULL")
                elif isinstance(v, bool):
                    vals.append("TRUE" if v else "FALSE")
                elif isinstance(v, (int, float)):
                    vals.append(str(v))
                else:
                    escaped = str(v).replace("'", "''")
                    vals.append(f"'{escaped}'")
            val_list = ", ".join(vals)
            output_lines.append(f'INSERT INTO public."{table}" ({col_list}) VALUES ({val_list});')

        output_lines.append("")  # blank line between tables

output_lines.append("-- Re-enable triggers / FK checks")
output_lines.append("SET session_replication_role = DEFAULT;\n")

conn.close()

out_path = os.path.join(os.path.dirname(__file__), "seed_data_export.sql")
with open(out_path, "w", encoding="utf-8") as f:
    f.write("\n".join(output_lines))

print(f"✅  Exported to: {out_path}")
for t in TABLES:
    print(f"   Table: {t}")
