"""add bundle system

Revision ID: 071cd0620984
Revises: 5970b8cf259f
Create Date: 2026-02-25 15:53:44.438298

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '071cd0620984'
down_revision: Union[str, Sequence[str], None] = '5970b8cf259f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bundles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bundle_name', sa.String(length=100), nullable=False),
    sa.Column('bundle_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_bundle_active', 'bundles', ['is_active'], unique=False)
    op.create_table('bundle_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bundle_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.CheckConstraint('quantity > 0', name='ck_bundle_quantity_positive'),
    sa.ForeignKeyConstraint(['bundle_id'], ['bundles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_bundle_item_bundle', 'bundle_items', ['bundle_id'], unique=False)
    op.create_index('ix_bundle_item_product', 'bundle_items', ['product_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_bundle_item_product', table_name='bundle_items')
    op.drop_index('ix_bundle_item_bundle', table_name='bundle_items')
    op.drop_table('bundle_items')
    op.drop_index('ix_bundle_active', table_name='bundles')
    op.drop_table('bundles')
    # ### end Alembic commands ###
