"""Add InventoryHealthAnalytics

Revision ID: 4eb3179fd4a7
Revises: 74a6e6c7d498
Create Date: 2026-03-02 02:20:48.607890

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4eb3179fd4a7'
down_revision: Union[str, Sequence[str], None] = '74a6e6c7d498'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sales_orders', 'expected_delivery_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sales_orders', sa.Column('expected_delivery_date', sa.DATE(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
