"""initial schema

Revision ID: 5970b8cf259f
Revises: 
Create Date: 2026-02-25 02:45:15.836301

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5970b8cf259f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('promotions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('discount_type', sa.Enum('PERCENTAGE', 'FIXED', 'QUANTITY_BASED', name='discount_type_enum'), nullable=False),
    sa.Column('discount_value', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('min_quantity', sa.Integer(), nullable=True),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('valid_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('approval_status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='approval_status_enum'), nullable=False),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('discount_value > 0', name='ck_discount_positive'),
    sa.CheckConstraint('valid_until IS NULL OR valid_until > valid_from', name='ck_valid_date_range'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_promotion_active', 'promotions', ['is_active'], unique=False)
    op.create_index('ix_promotion_product', 'promotions', ['product_id'], unique=False)
    op.create_index('ix_promotion_valid_window', 'promotions', ['valid_from', 'valid_until'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_promotion_valid_window', table_name='promotions')
    op.drop_index('ix_promotion_product', table_name='promotions')
    op.drop_index('ix_promotion_active', table_name='promotions')
    op.drop_table('promotions')
    # ### end Alembic commands ###
