"""Add previous_severity_score

Revision ID: 6e23431839ad
Revises: effc5cf7a56f
Create Date: 2026-03-02 03:15:01.285473

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e23431839ad'
down_revision: Union[str, Sequence[str], None] = 'effc5cf7a56f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventory_health_analytics', sa.Column('previous_severity_score', sa.Numeric(precision=10, scale=4), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inventory_health_analytics', 'previous_severity_score')
    # ### end Alembic commands ###
