"""Add hysteresis columns to inventory_health_analytics

Revision ID: 9ee8230cab25
Revises: 6e23431839ad
Create Date: 2026-03-05 17:58:07.883368

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ee8230cab25'
down_revision: Union[str, Sequence[str], None] = '6e23431839ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
