"""Add ProductLogisticsMetrics table

Revision ID: b5330f2557fa
Revises: a3f1d2e4b876
Create Date: 2026-02-28 18:57:40.595994

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5330f2557fa'
down_revision: Union[str, Sequence[str], None] = 'a3f1d2e4b876'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventory_optimization_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dead_days_threshold', sa.Integer(), nullable=False),
    sa.Column('slow_turnover_threshold', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('expiry_warning_days', sa.Integer(), nullable=False),
    sa.Column('auto_discount_enabled', sa.Boolean(), nullable=True),
    sa.Column('auto_bundle_enabled', sa.Boolean(), nullable=True),
    sa.Column('max_discount_limit', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('low_risk_severity_threshold', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product_logistics_metrics',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('item_popularity_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('picking_time_seconds', sa.Integer(), nullable=True),
    sa.Column('handling_cost_per_unit', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('stockout_count_last_month', sa.Integer(), nullable=True),
    sa.Column('order_fulfillment_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('total_orders_last_month', sa.Integer(), nullable=True),
    sa.Column('layout_efficiency_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('forecasted_demand_next_7d', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('kpi_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('product_id')
    )
    op.create_table('inventory_health_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=True),
    sa.Column('health_type', sa.Enum('DEAD', 'SLOW', 'EXPIRY', name='health_type_enum'), nullable=False),
    sa.Column('severity_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('detected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('severity_score >= 0 AND severity_score <= 100', name='ck_health_severity_range'),
    sa.ForeignKeyConstraint(['batch_id'], ['inventory.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_health_detected', 'inventory_health_status', ['detected_at'], unique=False)
    op.create_index('ix_health_product_wh_type', 'inventory_health_status', ['product_id', 'warehouse_id', 'health_type'], unique=False)
    op.create_index('ix_health_severity', 'inventory_health_status', ['severity_score'], unique=False)
    op.create_table('inventory_action_suggestions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=True),
    sa.Column('health_status_id', sa.Integer(), nullable=True),
    sa.Column('suggestion_type', sa.Enum('DISCOUNT', 'BUNDLE', 'DISPOSAL', 'RETURN', name='suggestion_type_enum'), nullable=False),
    sa.Column('reasoning', sa.Text(), nullable=False),
    sa.Column('severity_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('suggested_discount_percent', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('linked_promotion_id', sa.Integer(), nullable=True),
    sa.Column('linked_bundle_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'EXECUTED', name='suggestion_status_enum'), nullable=False),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint('severity_score >= 0 AND severity_score <= 100', name='ck_suggestion_severity_range'),
    sa.ForeignKeyConstraint(['batch_id'], ['inventory.id'], ),
    sa.ForeignKeyConstraint(['health_status_id'], ['inventory_health_status.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['linked_bundle_id'], ['bundles.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['linked_promotion_id'], ['promotions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_suggestion_product_wh', 'inventory_action_suggestions', ['product_id', 'warehouse_id'], unique=False)
    op.create_index('ix_suggestion_status', 'inventory_action_suggestions', ['status'], unique=False)
    op.create_index('ix_suggestion_type', 'inventory_action_suggestions', ['suggestion_type'], unique=False)
    op.drop_index(op.f('ix_delivery_notes_shipped_at'), table_name='delivery_notes')
    op.add_column('suppliers', sa.Column('allows_return', sa.Boolean(), nullable=True))
    op.add_column('suppliers', sa.Column('return_window_days', sa.Integer(), nullable=True))
    op.add_column('zones', sa.Column('product_category', sa.String(length=100), nullable=False, server_default='GENERAL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('zones', 'product_category')
    op.drop_column('suppliers', 'return_window_days')
    op.drop_column('suppliers', 'allows_return')
    op.create_index(op.f('ix_delivery_notes_shipped_at'), 'delivery_notes', ['shipped_at'], unique=False)
    op.drop_index('ix_suggestion_type', table_name='inventory_action_suggestions')
    op.drop_index('ix_suggestion_status', table_name='inventory_action_suggestions')
    op.drop_index('ix_suggestion_product_wh', table_name='inventory_action_suggestions')
    op.drop_table('inventory_action_suggestions')
    op.drop_index('ix_health_severity', table_name='inventory_health_status')
    op.drop_index('ix_health_product_wh_type', table_name='inventory_health_status')
    op.drop_index('ix_health_detected', table_name='inventory_health_status')
    op.drop_table('inventory_health_status')
    op.drop_table('product_logistics_metrics')
    op.drop_table('inventory_optimization_config')
    # ### end Alembic commands ###
