"""Upgrade InventoryHealthAnalytics V2

Revision ID: effc5cf7a56f
Revises: 4eb3179fd4a7
Create Date: 2026-03-02 02:55:40.127951

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'effc5cf7a56f'
down_revision: Union[str, Sequence[str], None] = '4eb3179fd4a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventory_health_analytics', sa.Column('velocity_score', sa.Numeric(precision=10, scale=4), nullable=False))
    op.add_column('inventory_health_analytics', sa.Column('normalized_velocity', sa.Numeric(precision=10, scale=4), nullable=False))
    op.add_column('inventory_health_analytics', sa.Column('overstock_ratio', sa.Numeric(precision=10, scale=4), nullable=False))
    op.add_column('inventory_health_analytics', sa.Column('coefficient_of_variation', sa.Numeric(precision=10, scale=4), nullable=False))
    op.add_column('inventory_health_analytics', sa.Column('previous_classification', sa.Enum('HEALTHY', 'SLOW_MOVING', 'DEAD', name='health_classification_enum'), nullable=True))
    op.add_column('inventory_health_analytics', sa.Column('consecutive_confirmation_count', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inventory_health_analytics', 'consecutive_confirmation_count')
    op.drop_column('inventory_health_analytics', 'previous_classification')
    op.drop_column('inventory_health_analytics', 'coefficient_of_variation')
    op.drop_column('inventory_health_analytics', 'overstock_ratio')
    op.drop_column('inventory_health_analytics', 'normalized_velocity')
    op.drop_column('inventory_health_analytics', 'velocity_score')
    # ### end Alembic commands ###
